name: Docker run

on: [push]

jobs:
  docker_job:
    runs-on: ubuntu-latest    
    name: docker job
    steps:
    - name: env clone
      run: |
        echo "Creating .env file..."
        touch .env
        echo GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} >> .env
    - name: docker use
    - uses: actions/checkout@v1
      run: echo "Docker running..."
    - uses: ./
